{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.modules.home.t3code;

  bootstrap = pkgs.writeShellApplication {
    name = "bootstrap-t3code";
    runtimeInputs = [
      pkgs.bash
      pkgs.curl
      pkgs.gnutar
      pkgs.gzip
      pkgs.coreutils
    ];
    text = ''
      if [ ! -x "$HOME/.local/bin/t3" ]; then
        curl -fsSL https://t3.codes/install.sh | sh
      fi
    '';
  };

  configureDesktopClient = pkgs.writeShellApplication {
    name = "configure-t3-desktop-client";
    runtimeInputs = [
      pkgs.coreutils
      pkgs.jq
    ];
    text = ''
      settings_dir="$HOME/.t3/userdata"
      settings="$settings_dir/desktop-settings.json"
      mkdir -p "$settings_dir"
      if [ -f "$settings" ] && jq -e '.localEnvironmentEnabled == false' "$settings" >/dev/null; then
        exit 0
      fi

      umask 077
      tmp=$(mktemp "$settings_dir/.desktop-settings.XXXXXX")
      trap 'rm -f "$tmp"' EXIT
      if [ -f "$settings" ]; then
        jq '.localEnvironmentEnabled = false' "$settings" > "$tmp"
      else
        printf '%s\n' '{"localEnvironmentEnabled":false}' > "$tmp"
      fi
      mv "$tmp" "$settings"
    '';
  };

  # T3's native service owns its launchd/systemd unit and its versioned,
  # writable runtime. Use only stable paths when it snapshots the Mac PATH.
  servicePath = lib.concatStringsSep ":" [
    "${config.home.homeDirectory}/.local/bin"
    "${config.home.homeDirectory}/.bun/bin"
    "/etc/profiles/per-user/${config.home.username}/bin"
    "/run/current-system/sw/bin"
    "/opt/homebrew/bin"
    "/usr/local/bin"
    "/usr/bin"
    "/bin"
    "/usr/sbin"
    "/sbin"
  ];
in
{
  options.modules.home.t3code.enable = lib.mkEnableOption "T3 Code server";

  config = lib.mkIf cfg.enable {
    # The service installer creates the user unit, while Home Manager owns
    # the bootstrapping rule and the provider PATH. T3 can then update the
    # running service from its web/mobile UI or with `t3 update`.
    home.activation.installT3Code = lib.hm.dag.entryAfter [ "installCodexCli" "installClaudeCode" ] ''
      run ${lib.getExe bootstrap}
    '';
    home.activation.installT3CodeService = lib.hm.dag.entryAfter [ "installT3Code" ] ''
      run ${pkgs.coreutils}/bin/env PATH="${servicePath}" "$HOME/.local/bin/t3" service install
    '';

    # The Homebrew app is a client of the persistent CLI service. Starting
    # its embedded local server would open the same T3 database twice.
    home.activation.configureT3DesktopClient = lib.mkIf pkgs.stdenv.hostPlatform.isDarwin (
      lib.hm.dag.entryAfter [ "installT3CodeService" ] ''
        run ${lib.getExe configureDesktopClient}
      ''
    );

    # T3's Linux unit is generated by its own updater. A drop-in keeps all
    # three provider commands visible to its background process.
    xdg.configFile = lib.mkIf pkgs.stdenv.hostPlatform.isLinux {
      "systemd/user/t3code.service.d/10-provider-path.conf".text = ''
        [Service]
        Environment="PATH=${servicePath}"
      '';
    };
  };
}
