{
  config,
  lib,
  pkgs,
  ...
}:
let
  bootstrap = pkgs.writeShellApplication {
    name = "bootstrap-t3code";
    runtimeInputs = [
      pkgs.bash
      pkgs.curl
      pkgs.gnutar
      pkgs.gzip
      pkgs.coreutils
    ];
    text = ''
      if [ ! -x "$HOME/.local/bin/t3" ]; then
        curl -fsSL https://t3.codes/install.sh | T3CODE_CHANNEL=nightly sh
      fi
    '';
  };

  configureDesktopClient = pkgs.writeShellApplication {
    name = "configure-t3-desktop-client";
    runtimeInputs = [
      pkgs.coreutils
      pkgs.jq
    ];
    text = ''
      settings_dir="$HOME/.t3/userdata"
      settings="$settings_dir/desktop-settings.json"
      mkdir -p "$settings_dir"
      if [ -f "$settings" ] && jq -e '.localEnvironmentEnabled == false and .updateChannel == "nightly" and .updateChannelConfiguredByUser == true' "$settings" >/dev/null; then
        exit 0
      fi

      umask 077
      tmp=$(mktemp "$settings_dir/.desktop-settings.XXXXXX")
      trap 'rm -f "$tmp"' EXIT
      if [ -f "$settings" ]; then
        jq '.localEnvironmentEnabled = false | .updateChannel = "nightly" | .updateChannelConfiguredByUser = true' "$settings" > "$tmp"
      else
        printf '%s\n' '{"localEnvironmentEnabled":false,"updateChannel":"nightly","updateChannelConfiguredByUser":true}' > "$tmp"
      fi
      mv "$tmp" "$settings"
    '';
  };

  # T3's native service owns its launchd/systemd unit and its versioned,
  # writable runtime. Use only stable paths when it snapshots the Mac PATH.
  serviceUnit =
    if pkgs.stdenv.hostPlatform.isDarwin then
      "$HOME/Library/LaunchAgents/com.t3tools.t3code.service.plist"
    else
      "${config.xdg.configHome}/systemd/user/t3code.service";

  servicePath = lib.concatStringsSep ":" [
    "${config.home.homeDirectory}/.local/bin"
    "${config.home.homeDirectory}/.bun/bin"
    "/etc/profiles/per-user/${config.home.username}/bin"
    "/run/current-system/sw/bin"
    "/opt/homebrew/bin"
    "/usr/local/bin"
    "/usr/bin"
    "/bin"
    "/usr/sbin"
    "/sbin"
  ];
in
{
  # T3 owns its service unit and runtime so it can update itself; Home
  # Manager only bootstraps it and pins the provider PATH.
  home.activation.installT3Code = lib.hm.dag.entryAfter [
    "installCodexCli"
    "installClaudeCode"
  ] ''
    run ${lib.getExe bootstrap}
  '';
  # Install the service once; T3 maintains its unit from then on. This also
  # keeps boot-time activation, which runs before the user manager exists,
  # from calling the installer.
  home.activation.installT3CodeService = lib.hm.dag.entryAfter [ "installT3Code" ] ''
    if [ ! -e "${serviceUnit}" ]; then
      run ${pkgs.coreutils}/bin/env PATH="${servicePath}" "$HOME/.local/bin/t3" service install
    fi
  '';

  # The Homebrew app is a client of the persistent CLI service. Starting
  # its embedded local server would open the same T3 database twice.
  home.activation.configureT3DesktopClient = lib.mkIf pkgs.stdenv.hostPlatform.isDarwin (
    lib.hm.dag.entryAfter [ "installT3CodeService" ] ''
      run ${lib.getExe configureDesktopClient}
    ''
  );

  # T3's Linux unit is generated by its own updater. A drop-in keeps all
  # provider commands visible to its background process.
  xdg.configFile = lib.mkIf pkgs.stdenv.hostPlatform.isLinux {
    "systemd/user/t3code.service.d/10-provider-path.conf".text = ''
      [Service]
      Environment="PATH=${servicePath}"
    '';
  };
}
